### ISSUE TITLE
Run fails if the 'data' directory already exists and has files

### ISSUE THREAD

**Issue by yolile** [open-contracting/kingfisher#166] opened 2018-07-23 17:34 UTC
I run ./ocds-cli run --run=uruguay for the first time after updating the project and I got:

```
Traceback (most recent call last):
  File "./ocdsdata-cli", line 28, in <module>
    main()
  File "./ocdsdata-cli", line 22, in main
    commands[args.subcommand].run_command(args)
  File "/home/yohanna/desarrollo/ocdsdata/ocdsdata/cli/commands/run.py", line 115, in run_command
    new_version=new_version
  File "/home/yohanna/desarrollo/ocdsdata/ocdsdata/base.py", line 114, in __init__
    self.metadata_db = MetadataDB(self.full_directory)
  File "/home/yohanna/desarrollo/ocdsdata/ocdsdata/metadata_db.py", line 60, in __init__
    with self.engine.begin() as connection:
  File "/home/yohanna/desarrollo/ocdsdata/.ve/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1992, in begin
    conn = self.contextual_connect(close_with_result=close_with_result)
  File "/home/yohanna/desarrollo/ocdsdata/.ve/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2123, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/yohanna/desarrollo/ocdsdata/.ve/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2162, in _wrap_pool_connect
    e, dialect, self)
  File "/home/yohanna/desarrollo/ocdsdata/.ve/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception_noconnection
    exc_info
  File "/home/yohanna/desarrollo/ocdsdata/.ve/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/yohanna/desarrollo/ocdsdata/.ve/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/home/yohanna/desarrollo/ocdsdata/.ve/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/home/yohanna/desarrollo/ocdsdata/.ve/lib/python3.5/site-packages/sqlalchemy/pool.py", line 403, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/yohanna/desarrollo/ocdsdata/.ve/lib/python3.5/site-packages/sqlalchemy/pool.py", line 784, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/yohanna/desarrollo/ocdsdata/.ve/lib/python3.5/site-packages/sqlalchemy/pool.py", line 532, in checkout
    rec = pool._do_get()
  File "/home/yohanna/desarrollo/ocdsdata/.ve/lib/python3.5/site-packages/sqlalchemy/pool.py", line 1280, in _do_get
    return self._create_connection()
  File "/home/yohanna/desarrollo/ocdsdata/.ve/lib/python3.5/site-packages/sqlalchemy/pool.py", line 350, in _create_connection
    return _ConnectionRecord(self)
  File "/home/yohanna/desarrollo/ocdsdata/.ve/lib/python3.5/site-packages/sqlalchemy/pool.py", line 477, in __init__
    self.__connect(first_connect_check=True)
  File "/home/yohanna/desarrollo/ocdsdata/.ve/lib/python3.5/site-packages/sqlalchemy/pool.py", line 667, in __connect
    connection = pool._invoke_creator(self)
  File "/home/yohanna/desarrollo/ocdsdata/.ve/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/yohanna/desarrollo/ocdsdata/.ve/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 410, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file (Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by odscjames** [comment] 2018-07-24 08:15
So for some reason, it thinks you should already have some files on disk, yet it can't access those files.  

In MetadataDB, just after self.metadata_file is created can you get it to print that? Then double check on your disk and see if the file does not exist. (It might exist with the wrong permissions?) 

If you don't have any data for Uruguay you want to keep, you can just delete data/uruguay and it should start working again.

But it would be good to work out what's going on here and see what we can improve.

**Comment by jpmckinney** [comment] 2019-01-31 17:05
Closing as assuming not a bug in Scrapy.

**Closed by jpmckinney** 2019-01-31 17:05 UTC
Labels: 2 Gather, 3 Fetch
